# Generated by Django 2.0.2 on 2018-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='rentalproduct',
            name='max_rental',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalproduct',
            name='max_rental_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='retire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
