# Generated by Django 2.0.2 on 2018-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180228_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='filename',
            field=models.TextField(),
        ),
    ]
